

services:

  api:
    build: .
    container_name: social_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: social_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7
    container_name: social_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s

  celery_worker:
    build: .
    container_name: social_celery
    command: celery -A src.celery_tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - db
    restart: always


volumes:
  postgres_data:
