"""Fix cascade deletes

Revision ID: 0646f84a45bf
Revises: c43d5244b9f4
Create Date: 2026-02-04 14:56:04.300033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0646f84a45bf'
down_revision: Union[str, Sequence[str], None] = 'c43d5244b9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blocks_blocker_id_fkey'), 'blocks', type_='foreignkey')
    op.drop_constraint(op.f('blocks_blocked_id_fkey'), 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'user_accounts', ['blocked_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blocks', 'user_accounts', ['blocker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_members_conversation_id_fkey'), 'conversation_members', type_='foreignkey')
    op.drop_constraint(op.f('conversation_members_user_id_fkey'), 'conversation_members', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_members', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_members', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('conversations_created_by_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'user_accounts', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('follows_follower_id_fkey'), 'follows', type_='foreignkey')
    op.drop_constraint(op.f('follows_following_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'user_accounts', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follows', 'user_accounts', ['following_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('media_user_tag_media_id_fkey'), 'media_user_tag', type_='foreignkey')
    op.drop_constraint(op.f('media_user_tag_tagged_user_id_fkey'), 'media_user_tag', type_='foreignkey')
    op.drop_constraint(op.f('media_user_tag_tagged_by_user_fkey'), 'media_user_tag', type_='foreignkey')
    op.create_foreign_key(None, 'media_user_tag', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media_user_tag', 'user_accounts', ['tagged_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media_user_tag', 'user_accounts', ['tagged_by_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'user_accounts', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('stories_user_id_fkey'), 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'user_accounts', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('story_views_story_id_fkey'), 'story_views', type_='foreignkey')
    op.drop_constraint(op.f('story_views_viewer_id_fkey'), 'story_views', type_='foreignkey')
    op.create_foreign_key(None, 'story_views', 'user_accounts', ['viewer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'story_views', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_views', type_='foreignkey')
    op.drop_constraint(None, 'story_views', type_='foreignkey')
    op.create_foreign_key(op.f('story_views_viewer_id_fkey'), 'story_views', 'user_accounts', ['viewer_id'], ['id'])
    op.create_foreign_key(op.f('story_views_story_id_fkey'), 'story_views', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key(op.f('stories_user_id_fkey'), 'stories', 'user_accounts', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'user_accounts', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'user_accounts', ['sender_id'], ['id'])
    op.drop_constraint(None, 'media_user_tag', type_='foreignkey')
    op.drop_constraint(None, 'media_user_tag', type_='foreignkey')
    op.drop_constraint(None, 'media_user_tag', type_='foreignkey')
    op.create_foreign_key(op.f('media_user_tag_tagged_by_user_fkey'), 'media_user_tag', 'user_accounts', ['tagged_by_user'], ['id'])
    op.create_foreign_key(op.f('media_user_tag_tagged_user_id_fkey'), 'media_user_tag', 'user_accounts', ['tagged_user_id'], ['id'])
    op.create_foreign_key(op.f('media_user_tag_media_id_fkey'), 'media_user_tag', 'media', ['media_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'user_accounts', ['user_id'], ['id'])
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_following_id_fkey'), 'follows', 'user_accounts', ['following_id'], ['id'])
    op.create_foreign_key(op.f('follows_follower_id_fkey'), 'follows', 'user_accounts', ['follower_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_created_by_fkey'), 'conversations', 'user_accounts', ['created_by'], ['id'])
    op.alter_column('conversations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_members_user_id_fkey'), 'conversation_members', 'user_accounts', ['user_id'], ['id'])
    op.create_foreign_key(op.f('conversation_members_conversation_id_fkey'), 'conversation_members', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'user_accounts', ['user_id'], ['id'])
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key(op.f('blocks_blocked_id_fkey'), 'blocks', 'user_accounts', ['blocked_id'], ['id'])
    op.create_foreign_key(op.f('blocks_blocker_id_fkey'), 'blocks', 'user_accounts', ['blocker_id'], ['id'])
    # ### end Alembic commands ###
