""" minor changes for relationship

Revision ID: 0891c7731b60
Revises: c044093d94a8
Create Date: 2026-01-15 13:45:57.864192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0891c7731b60'
down_revision: Union[str, Sequence[str], None] = 'c044093d94a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('following_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_follows_followed_id'), table_name='follows')
    op.drop_constraint(op.f('uq_follower_followed'), 'follows', type_='unique')
    op.create_unique_constraint('uq_follower_followed', 'follows', ['follower_id', 'following_id'])
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.drop_constraint(op.f('follows_followed_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'user_accounts', ['following_id'], ['id'])
    op.drop_column('follows', 'followed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('followed_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_followed_id_fkey'), 'follows', 'user_accounts', ['followed_id'], ['id'])
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_constraint('uq_follower_followed', 'follows', type_='unique')
    op.create_unique_constraint(op.f('uq_follower_followed'), 'follows', ['follower_id', 'followed_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_follows_followed_id'), 'follows', ['followed_id'], unique=False)
    op.drop_column('follows', 'following_id')
    # ### end Alembic commands ###
