"""init

Revision ID: 13e57d52109f
Revises: 
Create Date: 2026-01-08 15:52:11.648463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13e57d52109f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_accounts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user_accounts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.alter_column('user_accounts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_accounts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
