"""added created by in conversation table

Revision ID: 792ddf971ca7
Revises: db95d6bdfe1e
Create Date: 2026-01-27 15:27:09.187034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '792ddf971ca7'
down_revision: Union[str, Sequence[str], None] = 'db95d6bdfe1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'user_accounts', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'created_by')
    # ### end Alembic commands ###
