"""create media_user_tag table

Revision ID: b70cf440ef67
Revises: 28a38e250e7a
Create Date: 2026-01-20 13:12:44.671261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b70cf440ef67'
down_revision: Union[str, Sequence[str], None] = '28a38e250e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_user_tag_media_id_fkey'), 'media_user_tag', type_='foreignkey')
    op.create_foreign_key(None, 'media_user_tag', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_user_tag', type_='foreignkey')
    op.create_foreign_key(op.f('media_user_tag_media_id_fkey'), 'media_user_tag', 'posts', ['media_id'], ['id'])
    # ### end Alembic commands ###
